tealcrm/core/urls.py
from django.urls import path
from .views import index, about

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
]

tealcrm/lead/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.leads_list, name='leads_list'),
    path('<int:pk>/', views.leads_detail, name='leads_detail'),
    path('<int:pk>/delete/', views.leads_delete, name='leads_delete'),
    path('<int:pk>/convert/', views.convert_to_client, name='leads_convert'),
    path('<int:pk>/edit/', views.leads_edit, name='leads_edit'),
    path('add-lead/', views.add_lead, name='add_lead'),
]

tealcrm/tealcrm/urls.py
from django.contrib import admin
from django.urls import path, include
# from core.views import index


urlpatterns = [
    # path('', index, name='index'),
    path('', include('core.urls')),
    path('register/', include('userprofile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('clients/', include('client.urls')),
    # path('', include('userprofile.urls')),
    path('admin/', admin.site.urls),

]

tealcrm/lead/models.py
from django.contrib.auth.models import User
from django.db import models

class Lead(models.Model):
    LOW='low'
    MEDIUM='medium'
    HIGH='high'

    CHOICES_PRIORITY=(
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, "High"),
    )

    NEW = 'new'
    CONTACTED= 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    name=models.CharField(max_length=255)
    email=models.EmailField()
    description=models.TextField(blank=True, null=True)
    priority=models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status=models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client=models.BooleanField(default=False)
    create_by=models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    create_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

tealcrm/lead/forms.py
from django import forms
from .models import Lead

class AddLeadForm(forms.ModelForm):
    class Meta:
        model=Lead
        fields=('name', 'email', 'description', 'priority', 'status')

tealcrm/lead/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Lead
# from client.models import Client

from .forms import AddLeadForm
from client.models import Client


@login_required
def leads_list(request):
    leads = Lead.objects.filter(create_by=request.user, converted_to_client=False)


    return render(request, 'lead/leads_list.html', {
        'leads':leads
    })

@login_required
def leads_detail(request, pk):
    # lead=Lead.objects.filter(create_by=request.user).get(pk=pk)
    lead=get_object_or_404(Lead, create_by=request.user, pk=pk)

    return render(request, 'lead/leads_detail.html', {
        'lead':lead
    })

@login_required
def leads_delete(request, pk):
    lead=get_object_or_404(Lead, create_by=request.user, pk=pk)
    lead.delete()

    messages.success(request, 'The lead was deleted')

    return redirect('leads_list')

@login_required
def leads_edit(request, pk):
    lead=get_object_or_404(Lead, create_by=request.user, pk=pk)
    if request.method == 'POST':
        form=AddLeadForm(request.POST, instance=lead)

        if form.is_valid():
            form.save()

            messages.success(request, 'The changes was saved.')

            return redirect('leads_list')
    else:
        form=AddLeadForm(instance=lead)

    return render(request, 'lead/leads_edit.html',{
        'form':form
    })


@login_required
def add_lead(request):
    if request.method == 'POST':
        form = AddLeadForm(request.POST)

        if form.is_valid():
            lead=form.save(commit=False)
            lead.create_by=request.user
            lead.save()

            messages.success(request, 'The lead was created.')

            return redirect('leads_list')
    else:
        form=AddLeadForm()
    return render(request, 'lead/add_lead.html',{
        'form': form
    })


@login_required
def convert_to_client(request, pk):
    lead=get_object_or_404(Lead, create_by=request.user, pk=pk)
    client=Client.objects.create(
        name=lead.name,
        email=lead.email,
        description=lead.description,
        create_by=request.user,
    )
    lead.converted_to_client=True
    lead.save()

    messages.success(request, f'The lead: {lead.name}  was converted to client.')

    return redirect('leads_list')

tealcrm/lead/templates/lead/add_lead.html
{%extends 'core/base.html'%}

{%block title%} Add lead {%endblock%}

{%block content%}
    <div class="py-6 px-6 ">
        <h1 class="text-xl">Add lead</h1>
        <form method="post" action=".">
            {%csrf_token%}
            {{form.as_p}}
            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
        </form>
    </div>


{%endblock%}

tealcrm/lead/templates/lead/leads_detail.html
{%extends 'core/base.html'%}

{%block title%}{{lead.name}}{%endblock%}

{%block content%}
    <div class="py-6 px-6 ">
        <h1 class="mb-4 text-xl">{{lead.name}}</h1>
        {%if lead.description%}
            <p class="font-semibold">Name</p>
            <p class="mb-2">{{lead.description}}</p>
        {%endif%}
        <p class="font-semibold">Priority</p>
        <p class="mb-2">{{lead.get_priority_display}}</p>

        <p class="font-semibold">Status</p>
        <p class="mb-2">{{lead.get_status_display}}</p>

        <p class="font-semibold">Create at</p>
        <p class="mb-2">{{lead.create_at|date:"M-d-Y H:i"}}</p>

        <p class="font-semibold">Modifed at</p>
        <p class="mb-6">{{lead.modified_at|date:"M-d-Y H:i"}}</p>

        <hr class="my-4">
        <a href="{%url 'leads_edit' lead.id%}" class="py-2 px-4 rounded-xl text-white bg-blue-500">Edit</a>
        <a href="{%url 'leads_convert' lead.id%}" class="py-2 px-4 rounded-xl text-white bg-purple-500">Convert to client</a>

        <a href="{%url 'leads_delete' lead.id %}" class="py-2 px-4 rounded-xl text-white bg-red-700">Delete</a>
        <hr class="my-4">


        <a href="{%url 'leads_list' %}">Back to leads</a>
    </div>
{%endblock%}

tealcrm/lead/templates/lead/leads_edit.html
{%extends 'core/base.html'%}

{%block title%}
    Edit lead
{%endblock%}
{%block content%}
    <div class="px-6 py-6">
        <h1 class="text-xl">Edit lead</h1>
        <form method="POST" action=".">
            {%csrf_token%}
            {{form.as_p}}
            <a href=""></a>
            <button class=" my-2 py-4 px-4 bg-purple-600 text-white rounded-xl">Confirm</button>
        </form>
    </div>
{%endblock%}

tealcrm/lead/templates/lead/leads_list.html
{%extends 'core/base.html'%}

{%block title%}Leads{%endblock%}

{%block content%}
    <div class="py-6 px-6 ">
        <h1 class="mb-4 text-xl">Leads</h1>
        <a href="{% url 'add_lead' %}" class=" inline-block py-4 px-6 bg-purple-600 rounded-xl text-white ">Add lead</a>
        {%if leads%}
            <div class="mt-6 flex justify-between">
                <p class ="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
                <p class ="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
                <p class ="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
            </div>
            {%for lead in leads%}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' ''%}">
                        <a href="{%url 'leads_detail' lead.id%}">{{lead.name}}</a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' ''%}">{{lead.get_priority_display}}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' ''%}">{{lead.get_status_display}}</p>
                </div>
            {%endfor%}
        {%else%}
            <p class="mt-5 px-2">There are no leads in the database yet...</p>
        {%endif%}
    </div>


{%endblock%}